### ISSUE TITLE
Widescreen and alt tab bug fixes

### ISSUE THREAD

**Issue by TheVektor** [J0shES/samp#20]
https://github.com/IgnatBantserov/sacm/blob/master/client/game/patches.cpp#L107-L115
Please take a look at this. I cant select 1366x768 in device selector because this patch is missing in 0.2 series.

**Comment by J0shES** [comment]
Fixed in https://github.com/J0shES/samp/commit/c74b1f3e2e3ed1002ad8448fe682bc099b181cd3
