### ISSUE TITLE
Launcher query fix

### ISSUE THREAD

**Issue by TheVektor** [J0shES/samp#21]
https://github.com/P3ti/RakSAMP/blob/c5ddb3c79dbf974471bb5088803c14df486d48fe/raknet/SocketLayer.cpp#L418-L422

https://github.com/P3ti/RakSAMP/blob/c5ddb3c79dbf974471bb5088803c14df486d48fe/server/src/query.cpp

**Comment by J0shES** [comment]
Mostly fixed in https://github.com/J0shES/samp/commit/c74b1f3e2e3ed1002ad8448fe682bc099b181cd3 but only 2 rules are being sent

**Comment by J0shES** [comment]
Fixed in new server core.
