### ISSUE TITLE
Add proper README with build instructions

### ISSUE THREAD

**Issue by 123marvin123** [J0shES/samp#22]
It would be great if there would be a proper README file including build instructions and a list of working and not working features.

**Comment by J0shES** [comment]
My build instructions are very terrible, but there should be no errors anyway, especially on DEBUG mode. See commit https://github.com/J0shES/samp/commit/b44ef1bd5bd0045b93a19405a98c282c599b540e

**Comment by 123marvin123** [comment]
Thanks.

There are actually some issues I ran into when trying to build the project in VS 2017:
- DirectX 9 SDK must be installed
- When building the server, I got a redefinition error of int32_t and uint32_t in amx.h which can be resolved by defining HAVESTDINT_H

**Comment by J0shES** [comment]
I've added the DX9 SDK requirement in the build "instructions".
I've also pushed that fix to master, thanks for reporting.
